---
title: "Decision Tree Regression"
output:
  html_document:
    theme: flatly
    highlight: pygments
    toc_depth: 5
    #### code_download: true
    #### code_folding: show
    toc: true
    toc_float:
      collapsed: false
    #### df_print: kable
---

#### Importing the dataset
```{r}
dataset = read.csv('https://pastebin.com/raw/L3DqdzAt')
dataset = dataset[2:3]
```

```{r}
#### Splitting the dataset into the Training set and Test set
#### install.packages('caTools')
#### library(caTools)
####  set.seed(123)
#### split = sample.split(dataset$Salary, SplitRatio = 2/3)
#### training_set = subset(dataset, split == TRUE)
#### test_set = subset(dataset, split == FALSE)

#### Feature Scaling
#### training_set = scale(training_set)
#### test_set = scale(test_set)
```

#### Fitting Decision Tree Regression to the dataset
```{r}
library(rpart)
regressor = rpart(formula = Salary ~ .,
                  data = dataset,
                  control = rpart.control(minsplit = 1))
```


#### Predicting a new result with Decision Tree Regression
```{r}
y_pred = predict(regressor, data.frame(Level = 6.5))
```


#### Visualising the Decision Tree Regression results (higher resolution)
```{r}
library(ggplot2)
x_grid = seq(min(dataset$Level), max(dataset$Level), 0.01)
ggplot() +
  geom_point(aes(x = dataset$Level, y = dataset$Salary),
             colour = 'red') +
  geom_line(aes(x = x_grid, y = predict(regressor, newdata = data.frame(Level = x_grid))),
            colour = 'blue') +
  ggtitle('Truth or Bluff (Decision Tree Regression)') +
  xlab('Level') +
  ylab('Salary')
```


#### Plotting the tree
```{r}
plot(regressor)
text(regressor)
```


