---
title: "Decision Tree Classification"
output:
  html_document:
    theme: flatly
    highlight: pygments
    toc_depth: 5
    # code_download: true
    # code_folding: show
    toc: true
    toc_float:
      collapsed: false
    # df_print: kable
---

#### Importing the dataset
```{r}
dataset = read.csv('https://pastebin.com/raw/ibZZwG51')
dataset = dataset[3:5]
```


#### Encoding the target feature as factor
```{r}
dataset$Purchased = factor(dataset$Purchased, levels = c(0, 1))
```


#### Splitting the dataset into the Training set and Test set

```{r}
library(caTools)
set.seed(123)
split = sample.split(dataset$Purchased, SplitRatio = 0.75)
training_set = subset(dataset, split == TRUE)
test_set = subset(dataset, split == FALSE)
```


#### Feature Scaling
```{r}
training_set[-3] = scale(training_set[-3])
test_set[-3] = scale(test_set[-3])
```


#### Fitting Decision Tree Classification to the Training set
```{r}
library(rpart)
classifier = rpart(formula = Purchased ~ .,
                   data = training_set)
```


#### Predicting the Test set results
```{r}
y_pred = predict(classifier, newdata = test_set[-3], type = 'class')
```


#### Making the Confusion Matrix
```{r}
cm = table(test_set[, 3], y_pred)
```


#### Visualising the Training set results
```{r}
library(ElemStatLearn)
set = training_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
y_grid = predict(classifier, newdata = grid_set, type = 'class')
plot(set[, -3],
     main = 'Decision Tree Classification (Training set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))
```


#### Visualising the Test set results
```{r}
library(ElemStatLearn)
set = test_set
X1 = seq(min(set[, 1]) - 1, max(set[, 1]) + 1, by = 0.01)
X2 = seq(min(set[, 2]) - 1, max(set[, 2]) + 1, by = 0.01)
grid_set = expand.grid(X1, X2)
colnames(grid_set) = c('Age', 'EstimatedSalary')
y_grid = predict(classifier, newdata = grid_set, type = 'class')
plot(set[, -3], main = 'Decision Tree Classification (Test set)',
     xlab = 'Age', ylab = 'Estimated Salary',
     xlim = range(X1), ylim = range(X2))
contour(X1, X2, matrix(as.numeric(y_grid), length(X1), length(X2)), add = TRUE)
points(grid_set, pch = '.', col = ifelse(y_grid == 1, 'springgreen3', 'tomato'))
points(set, pch = 21, bg = ifelse(set[, 3] == 1, 'green4', 'red3'))
```


#### Plotting the tree
```{r}
plot(classifier)
text(classifier)
```


