---
title: "Hierarchical Clustering"
output:
  html_document:
    theme: flatly
    highlight: pygments
    toc_depth: 5
    #  code_download: true
    #  code_folding: show
    toc: true
    toc_float:
      collapsed: false
    #  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Importing the dataset
```{r}
dataset = read.csv('https://pastebin.com/raw/3X04JmTa')
dataset = dataset[4:5]
```

#### Using the dendrogram to find the optimal number of clusters
```{r}
dendrogram = hclust(d = dist(dataset, method = 'euclidean'), method = 'ward.D')
plot(dendrogram,
     main = paste('Dendrogram'),
     xlab = 'Customers',
     ylab = 'Euclidean distances')
```


#### Fitting Hierarchical Clustering to the dataset
```{r}
hc = hclust(d = dist(dataset, method = 'euclidean'), method = 'ward.D')
y_hc = cutree(hc, 5)
```


#### Visualising the clusters
```{r}
library(cluster)
clusplot(dataset,
         y_hc,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels= 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste('Clusters of customers'),
         xlab = 'Annual Income',
         ylab = 'Spending Score')
```

