---
title: "K-Means Clustering"
output:
  html_document:
    theme: flatly
    highlight: pygments
    toc_depth: 5
    #  code_download: true
    #  code_folding: show
    toc: true
    toc_float:
      collapsed: false
    #  df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```

#### Importing the dataset
```{r}
dataset = read.csv('https://pastebin.com/raw/3X04JmTa')
dataset = dataset[4:5]
```


#### Using the elbow method to find the optimal number of clusters
```{r}
set.seed(6)
wcss = vector()
for (i in 1:10) wcss[i] = sum(kmeans(dataset, i)$withinss)
plot(1:10,
     wcss,
     type = 'b',
     main = paste('The Elbow Method'),
     xlab = 'Number of clusters',
     ylab = 'WCSS')
```


#### Fitting K-Means to the dataset
```{r}
set.seed(29)
kmeans = kmeans(x = dataset, centers = 5)
y_kmeans = kmeans$cluster
```


#### Visualising the clusters
```{r}
library(cluster)
clusplot(dataset,
         y_kmeans,
         lines = 0,
         shade = TRUE,
         color = TRUE,
         labels = 2,
         plotchar = FALSE,
         span = TRUE,
         main = paste('Clusters of customers'),
         xlab = 'Annual Income',
         ylab = 'Spending Score')
```

